In [6]:
import numpy as np
a=np.array([1,2,3])
print(a)
print(type(a))
print(a.shape)
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)
print(a[0,0],a[0,1],a[1,0])
b=np.zeros((2,2))
print(b)
c=np.ones((1,2))
print(c)
c = np.full((2,2), 7)  # Create a constant array
print(c)
d = np.eye(3)         # Create a 2x2 identity matrix
print(d)

[1 2 3]
<class 'numpy.ndarray'>
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)
1 2 4
[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
e = np.random.random((2,2))  # Create an array filled with random values
print(e)

[[0.54764769 0.37275435]
 [0.02400077 0.98351353]]


In [12]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
b = a[:2, 1:3]
print(b)
print(a[0,1])
b[0, 0] = 77
print(a[0,1])

[[2 3]
 [6 7]]
2
77


In [13]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [14]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [15]:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  #

[1 6 9]
[2 2]
[2 2]


In [16]:


x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)

int64
float64
int64


In [17]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [19]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

# Original code with error fixed: using range() to iterate over indices
# This performs element-wise multiplication using explicit loops
for i in range(len(x)):
  for j in range(len(x[i])):
    x[i][j]=x[i][j]*y[i][j]
print("Result using corrected explicit loops:")
print(x)


# More efficient and idiomatic NumPy way for element-wise multiplication
# This method is generally preferred for performance with NumPy arrays.
x_efficient = np.array([[1,2],[3,4]]) # Re-initialize x for this example
y_efficient = np.array([[5,6],[7,8]]) # Re-initialize y for this example
result_efficient = x_efficient * y_efficient
print("\nResult using NumPy's element-wise multiplication (x * y):")
print(result_efficient)

# Another NumPy way using np.multiply function:
# result_efficient_func = np.multiply(x_efficient, y_efficient)
# print(result_efficient_func)

Result using corrected explicit loops:
[[ 5 12]
 [21 32]]

Result using NumPy's element-wise multiplication (x * y):
[[ 5 12]
 [21 32]]


In [ ]:

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

In [20]:
x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  #

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [23]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] +v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [24]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
